--- !ditz.rubyforge.org,2008-03-06/project 
name: upfuckr
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: upfuckr
- !ditz.rubyforge.org,2008-03-06/component 
  name: tools
- !ditz.rubyforge.org,2008-03-06/component 
  name: droid
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: learn
  status: :unreleased
  release_time: 
  log_events: 
  - - 2010-06-09 00:55:31.057991 Z
    - Matt Katz <mattkatz@ubuntu>
    - created
    - I dont know what the hell I am doing
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.1"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2010-06-09 01:39:41.908849 Z
    - Matt Katz <mattkatz@ubuntu>
    - created
    - basic elements
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.2"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2010-06-09 01:48:22.264947 Z
    - Matt Katz <mattkatz@ubuntu>
    - created
    - usability improvements.
