--- !ditz.rubyforge.org,2008-03-06/project 
name: upfuckr
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: upfuckr
- !ditz.rubyforge.org,2008-03-06/component 
  name: tools
- !ditz.rubyforge.org,2008-03-06/component 
  name: droid
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: learn
  status: :released
  release_time: 2010-06-25 12:03:43.695135 Z
  log_events: 
  - - 2010-06-09 00:55:31.057991 Z
    - Matt Katz <mattkatz@ubuntu>
    - created
    - I dont know what the hell I am doing
  - - 2010-06-25 12:03:43.695168 Z
    - Matt Katz <mattkatz@ubuntu>
    - released
    - |-
      done with the tutorials.
      learned to go on vim
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.1"
  status: :released
  release_time: 2010-08-18 01:01:25.282298 Z
  log_events: 
  - - 2010-06-09 01:39:41.908849 Z
    - Matt Katz <mattkatz@ubuntu>
    - created
    - basic elements
  - - 2010-08-18 01:01:25.282332 Z
    - Matt Katz <mattkatz@ubuntu>
    - released
    - It installs! It Uploads! Huzzah! <img src="http://chart.apis.google.com/chart?cht=qr&chs=300x300&chl=http://github.com/downloads/mattkatz/UpFuckr/upfuckr-0.1.apk" />
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.2"
  status: :released
  release_time: 2011-08-25 01:33:34.226954 Z
  log_events: 
  - - 2010-06-09 01:48:22.264947 Z
    - Matt Katz <mattkatz@ubuntu>
    - created
    - usability improvements.
  - - 2011-08-25 01:33:34.226980 Z
    - Matt Katz <mattkatz@ubuntu>
    - released
    - ready to go!
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.3"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2010-12-08 02:12:24.753753 Z
    - Matt Katz <mattkatz@ubuntu>
    - created
    - Setting information for a picture
